from pathlib import Path

def write_lf(path, lines):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")

def write_crlf(path, lines):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text("\r\n".join(lines) + "\r\n", encoding="utf-8", newline="")

FILES = {
    '.github/workflows/build.yml': [
        '# Rewritten by scripts/rewrite_multiline_files.py using explicit line lists.',
        'name: DeadZone ROM Kitchen',
        '',
        'on:',
        '  workflow_dispatch:',
        '    inputs:',
        '      rom_url:',
        '        description: "OTA zip direct download URL"',
        '        required: true',
        '        default: "https://bkt-sgp-miui-ota-update-alisgp.oss-ap-southeast-1.aliyuncs.com/OS3.0.303.0.WNOCNXM/zircon-ota_full-OS3.0.303.0.WNOCNXM-user-16.0-09c35a83d6.zip"',
        '        type: string',
        '      device_codename:',
        '        description: "Device codename matching devices/<codename>.conf"',
        '        required: true',
        '        default: "zircon"',
        '        type: string',
        '      build_name:',
        '        description: "Build name"',
        '        required: true',
        '        default: "DeadZone_v1"',
        '        type: string',
        '      output_type:',
        '        description: "Output artifact type"',
        '        required: true',
        '        default: "fastboot_zip"',
        '        type: choice',
        '        options:',
        '          - "super_zst"',
        '          - "fastboot_zip"',
        '          - "full_release"',
        '      fs_mode:',
        '        description: "Dynamic partition filesystem handling"',
        '        required: true',
        '        default: "erofs"',
        '        type: choice',
        '        options:',
        '          - "preserve"',
        '          - "erofs"',
        '      vbmeta_mode:',
        '        description: "vbmeta patch mode"',
        '        required: true',
        '        default: "3"',
        '        type: choice',
        '        options:',
        '          - "0"',
        '          - "1"',
        '          - "2"',
        '          - "3"',
        '      patch_level:',
        '        description: "ROM modification level"',
        '        required: true',
        '        default: "none"',
        '        type: choice',
        '        options:',
        '          - "none"',
        '          - "safe"',
        '          - "full"',
        '      upload_pixeldrain:',
        '        description: "Upload final ZIP to PixelDrain"',
        '        required: true',
        '        default: true',
        '        type: boolean',
        '      notify_telegram:',
        '        description: "Send Telegram notification"',
        '        required: true',
        '        default: true',
        '        type: boolean',
        '      create_github_release:',
        '        description: "Create or update GitHub Release"',
        '        required: true',
        '        default: true',
        '        type: boolean',
        '      skip_patches:',
        '        description: "Legacy Phase 1 switch; keep true for first builds"',
        '        required: true',
        '        default: "true"',
        '        type: choice',
        '        options:',
        '          - "true"',
        '          - "false"',
        '',
        'permissions:',
        '  contents: write',
        '',
        'jobs:',
        '  kitchen:',
        '    name: Build DeadZone package',
        '    runs-on: ubuntu-latest',
        '',
        '    steps:',
        '      - name: Checkout',
        '        uses: actions/checkout@v4',
        '',
        '      - name: Free disk space',
        '        run: |',
        '          echo "=== Disk before ==="',
        '          df -h /',
        '          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc || true',
        '          sudo rm -rf /usr/local/share/boost "$AGENT_TOOLSDIRECTORY" || true',
        '          sudo apt-get clean',
        '          docker rmi $(docker image ls -aq) 2>/dev/null || true',
        '          echo "=== Disk after ==="',
        '          df -h /',
        '',
        '      - name: Install dependencies',
        '        run: |',
        '          sudo apt-get update',
        '          sudo apt-get install -y --no-install-recommends \\',
        '            aria2 \\',
        '            unzip \\',
        '            zip \\',
        '            p7zip-full \\',
        '            zstd \\',
        '            brotli \\',
        '            lz4 \\',
        '            jq \\',
        '            file \\',
        '            curl \\',
        '            git \\',
        '            gh \\',
        '            ca-certificates \\',
        '            tar \\',
        '            xz-utils \\',
        '            e2fsprogs \\',
        '            erofs-utils \\',
        '            android-sdk-libsparse-utils',
        '',
        '      - name: Setup tools',
        '        run: |',
        '          bash core/setup_tools.sh',
        '',
        '      - name: Debug tool paths',
        '        if: always()',
        '        run: |',
        '          echo "=== bin/ ==="',
        '          ls -lah bin || true',
        '          echo "=== tool paths ==="',
        '          # Keep this list aligned with required tool names.',
        '          which payload-dumper-go lpmake lpdump lpunpack simg2img img2simg zstd brotli lz4 gh || true',
        '          echo "=== tool verification log ==="',
        '          cat logs/tool-verification.log 2>/dev/null || true',
        '',
        '      - name: Run DeadZone kitchen',
        '        env:',
        '          BUILD_NAME: ${{ github.event.inputs.build_name }}',
        '          FS_MODE: ${{ github.event.inputs.fs_mode }}',
        '          VBMETA_MODE: ${{ github.event.inputs.vbmeta_mode }}',
        '          PATCH_LEVEL: ${{ github.event.inputs.patch_level }}',
        '          UPLOAD_PIXELDRAIN: ${{ github.event.inputs.upload_pixeldrain }}',
        '          NOTIFY_TELEGRAM: ${{ github.event.inputs.notify_telegram }}',
        '          CREATE_GITHUB_RELEASE: ${{ github.event.inputs.create_github_release }}',
        '          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}',
        '          PIXELDRAIN_API_KEY: ${{ secrets.PIXELDRAIN_API_KEY }}',
        '          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}',
        '          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}',
        '        run: |',
        '          chmod +x main.sh core/*.sh bin/* 2>/dev/null || true',
        '          bash -n main.sh core/*.sh',
        '          ./main.sh \\',
        '            "${{ github.event.inputs.rom_url }}" \\',
        '            "${{ github.event.inputs.device_codename }}" \\',
        '            "${{ github.event.inputs.skip_patches }}" \\',
        '            "${{ github.event.inputs.output_type }}" \\',
        '            "${{ github.event.inputs.fs_mode }}" \\',
        '            "${{ github.event.inputs.vbmeta_mode }}" \\',
        '            "${{ github.event.inputs.patch_level }}"',
        '',
        '      - name: Output info',
        '        if: always()',
        '        run: |',
        '          echo "=== output/ ==="',
        '          ls -lh output/ 2>/dev/null || true',
        '          echo "=== output/images/ ==="',
        '          ls -lh output/images/ 2>/dev/null || true',
        '          echo "=== output/logs/ ==="',
        '          ls -lh output/logs/ 2>/dev/null || true',
        '          echo "=== output_final/ ==="',
        '          ls -lh output_final/ 2>/dev/null || true',
        '          echo "=== partitions.tsv ==="',
        '          cat partitions.tsv 2>/dev/null || true',
        '',
        '      - name: Upload logs on failure',
        '        if: failure()',
        '        uses: actions/upload-artifact@v4',
        '        with:',
        '          name: deadzone-${{ github.event.inputs.device_codename }}-failure-logs',
        '          path: |',
        '            output/logs/',
        '            logs/',
        '            partitions.tsv',
        '          retention-days: 7',
        '',
        '      - name: Upload build artifacts',
        '        if: success()',
        '        uses: actions/upload-artifact@v4',
        '        with:',
        '          name: deadzone-${{ github.event.inputs.device_codename }}-${{ github.event.inputs.output_type }}',
        '          path: |',
        '            output/super.img.zst',
        '            output/images/super.img',
        '            output_final/',
        '            output/logs/',
        '            partitions.tsv',
        '          retention-days: 7',
    ],
    'core/package_fastboot.sh': [
        '#!/usr/bin/env bash',
        'set -euo pipefail',
        '# Rewritten by scripts/rewrite_multiline_files.py using explicit line lists.',
        '',
        'FASTBOOT_FLASH_ORDER="apusys audio_dsp boot ccu connsys_bt connsys_gnss connsys_wifi dpm dtbo gpueb gz init_boot lk logo mcf_ota mcupm md1img mvpu_algo pi_img preloader_raw scp spmfw sspm tee vbmeta vbmeta_system vbmeta_vendor vcp vendor_boot super"',
        '',
        '_fastboot_target_for_image() {',
        '  local img="$1"',
        '  local part="${img%.img}"',
        '  [[ "$part" == "super" ]] && {',
        "    printf 'super'",
        '    return',
        '  }',
        '  printf \'%s_ab\' "$part"',
        '}',
        '',
        '_write_bat_header() {',
        '  local file="$1"',
        '  {',
        "    printf '@echo off\\r\\n'",
        "    printf 'cd %%~dp0\\r\\n'",
        "    printf 'set fastboot=bin\\\\windows\\\\fastboot.exe\\r\\n'",
        "    printf 'if not exist %%fastboot%% echo %%fastboot%% not found. ^& pause ^& exit /B 1\\r\\n'",
        "    printf 'echo Waiting for device...\\r\\n'",
        "    printf 'set device=unknown\\r\\n'",
        '    printf \'for /f "tokens=2" %%%%D in (\'\\\'\'%%fastboot%% getvar product 2^>^&1 ^| findstr /l /b /c:"product:"\'\\\'\') do set device=%%%%D\\r\\n\'',
        "    printf '\\r\\n'",
        "    printf 'echo Detected device: %%device%%\\r\\n'",
        "    printf '\\r\\n'",
        '  } > "$file"',
        '}',
        '',
        '_write_windows_flash_lines() {',
        '  local file="$1"',
        '  local part img target',
        '  for part in $FASTBOOT_FLASH_ORDER; do',
        '    img="$OUTPUT_FINAL/images/$part.img"',
        '    [[ -s "$img" ]] || continue',
        '    target="$(_fastboot_target_for_image "$part.img")"',
        '    printf \'%%fastboot%% flash %s images\\\\%s.img\\r\\n\' "$target" "$part" >> "$file"',
        '  done',
        '}',
        '',
        '_write_windows_install_and_format_data() {',
        '  local file="$OUTPUT_FINAL/windows_install_and_format_data.bat"',
        '  _write_bat_header "$file"',
        '  {',
        "    printf 'echo WARNING: This will erase metadata and userdata.\\r\\n'",
        '    printf \'choice /C YN /M "Continue with format data install?"\\r\\n\'',
        "    printf 'if errorlevel 2 exit /B 1\\r\\n'",
        "    printf '%%fastboot%% set_active a\\r\\n'",
        '  } >> "$file"',
        '  _write_windows_flash_lines "$file"',
        '  {',
        "    printf '%%fastboot%% erase metadata\\r\\n'",
        "    printf '%%fastboot%% erase userdata\\r\\n'",
        "    printf '%%fastboot%% reboot\\r\\n'",
        '  } >> "$file"',
        '}',
        '',
        '_write_windows_install_upgrade() {',
        '  local file="$OUTPUT_FINAL/windows_install_upgrade.bat"',
        '  _write_bat_header "$file"',
        '  printf \'%%fastboot%% set_active a\\r\\n\' >> "$file"',
        '  _write_windows_flash_lines "$file"',
        '  printf \'%%fastboot%% reboot\\r\\n\' >> "$file"',
        '}',
        '',
        '_write_windows_format_data_only() {',
        '  local file="$OUTPUT_FINAL/windows_format_data_only.bat"',
        '  _write_bat_header "$file"',
        '  {',
        "    printf 'echo WARNING: This will erase metadata and userdata.\\r\\n'",
        '    printf \'choice /C YN /M "Continue with format data?"\\r\\n\'',
        "    printf 'if errorlevel 2 exit /B 1\\r\\n'",
        "    printf '%%fastboot%% set_active a\\r\\n'",
        "    printf '%%fastboot%% erase metadata\\r\\n'",
        "    printf '%%fastboot%% erase userdata\\r\\n'",
        "    printf '%%fastboot%% reboot\\r\\n'",
        '  } >> "$file"',
        '}',
        '',
        '_stage_windows_platform_tools_from_template_zip() {',
        '  local template_zip="$WORKSPACE/DeadZone Fastboot Script.zip"',
        '  local tmp',
        '  [[ -s "$template_zip" ]] || return 1',
        '  require_tool unzip',
        '  tmp="$(mktemp -d)"',
        '  unzip -q "$template_zip" -d "$tmp" || {',
        '    rm -rf "$tmp"',
        '    return 1',
        '  }',
        '  local src',
        '  for src in fastboot.exe AdbWinApi.dll AdbWinUsbApi.dll; do',
        '    local found',
        '    found="$(find "$tmp" -type f -path "*/bin/windows/$src" -o -type f -name "$src" | head -n 1 || true)"',
        '    [[ -n "$found" ]] || {',
        '      rm -rf "$tmp"',
        '      return 1',
        '    }',
        '    cp -f "$found" "$OUTPUT_FINAL/bin/windows/$src"',
        '  done',
        '  rm -rf "$tmp"',
        '}',
        '',
        '_download_windows_platform_tools() {',
        '  require_tool curl',
        '  require_tool unzip',
        '  local tmp url',
        '  tmp="$(mktemp -d)"',
        '  url="https://dl.google.com/android/repository/platform-tools-latest-windows.zip"',
        '  curl -fL "$url" -o "$tmp/platform-tools-windows.zip"',
        '  unzip -q "$tmp/platform-tools-windows.zip" -d "$tmp"',
        '  cp -f "$tmp/platform-tools/fastboot.exe" "$OUTPUT_FINAL/bin/windows/fastboot.exe"',
        '  cp -f "$tmp/platform-tools/AdbWinApi.dll" "$OUTPUT_FINAL/bin/windows/AdbWinApi.dll"',
        '  cp -f "$tmp/platform-tools/AdbWinUsbApi.dll" "$OUTPUT_FINAL/bin/windows/AdbWinUsbApi.dll"',
        '  rm -rf "$tmp"',
        '}',
        '',
        '_stage_windows_platform_tools() {',
        '  mkdir -p "$OUTPUT_FINAL/bin/windows"',
        '  if _stage_windows_platform_tools_from_template_zip; then',
        '    log "Staged Windows fastboot tools from DeadZone template zip"',
        '  else',
        '    log "Downloading official Android platform-tools for Windows fastboot files"',
        '    _download_windows_platform_tools',
        '  fi',
        '  [[ -s "$OUTPUT_FINAL/bin/windows/fastboot.exe" ]] || die "Missing bin/windows/fastboot.exe"',
        '  [[ -s "$OUTPUT_FINAL/bin/windows/AdbWinApi.dll" ]] || die "Missing bin/windows/AdbWinApi.dll"',
        '  [[ -s "$OUTPUT_FINAL/bin/windows/AdbWinUsbApi.dll" ]] || die "Missing bin/windows/AdbWinUsbApi.dll"',
        '}',
        '',
        '_image_list() {',
        '  find "$OUTPUT/images" -maxdepth 1 -type f -name \'*.img\' -printf \'%f\\n\' | sort',
        '}',
        '',
        'generate_pre_zip_sha256sums() {',
        '  local zip_name="${BUILD_NAME}_${DEVICE_CODENAME}_fastboot.zip"',
        '  local sums="$OUTPUT_FINAL/sha256sums.txt"',
        '',
        '  : > "$sums"',
        '  (',
        '    cd "$OUTPUT_FINAL"',
        '',
        '    log "Hashing staged images" >&2',
        "    if find images -type f -name '*.img' -print -quit | grep -q .; then",
        "      find images -type f -name '*.img' -print0 | sort -z | xargs -0 sha256sum",
        '    else',
        '      echo "::error::No images found for sha256" >&2',
        '      exit 1',
        '    fi',
        '',
        '    if [[ -d bin ]]; then',
        '      find bin -type f -print0 | sort -z | xargs -0 sha256sum',
        '    fi',
        '    for file in windows_install_and_format_data.bat windows_install_upgrade.bat windows_format_data_only.bat; do',
        '      [[ -f "$file" ]] && sha256sum "$file"',
        '    done',
        '',
        '    if [[ -f "$zip_name" ]]; then',
        '      log "Hashing final ZIP" >&2',
        '      sha256sum "$zip_name"',
        '    else',
        '      log "ZIP not created yet; skipping ZIP hash for now" >&2',
        '      echo "# $zip_name not created yet; ZIP hash will be added after packaging"',
        '    fi',
        '  ) > "$sums"',
        '',
        '  log "sha256sums generated"',
        '}',
        '',
        'generate_final_zip_sha256() {',
        '  local zip_name="${BUILD_NAME}_${DEVICE_CODENAME}_fastboot.zip"',
        '  local zip_file="$OUTPUT_FINAL/$zip_name"',
        '',
        '  [[ -s "$zip_file" ]] || die "Final ZIP missing for sha256: $zip_file"',
        '  log "Hashing final ZIP"',
        '  (cd "$OUTPUT_FINAL" && sha256sum "$zip_name") > "$OUTPUT_FINAL/$zip_name.sha256"',
        '  grep "  $zip_name$" "$OUTPUT_FINAL/$zip_name.sha256" >> "$OUTPUT_FINAL/sha256sums.txt"',
        '  log "sha256sums generated"',
        '}',
        '',
        'refresh_build_info() {',
        '  local zip_file="$OUTPUT_FINAL/${BUILD_NAME}_${DEVICE_CODENAME}_fastboot.zip"',
        '  local pd_link gh_link',
        '  pd_link="$(grep \'^PIXELDRAIN_URL=\' "$OUTPUT_FINAL/upload_links.txt" 2>/dev/null | cut -d= -f2- || true)"',
        '  gh_link="$(grep \'^GITHUB_RELEASE_URL=\' "$OUTPUT_FINAL/upload_links.txt" 2>/dev/null | cut -d= -f2- || true)"',
        '',
        '  {',
        '    echo "Build name: $BUILD_NAME"',
        '    echo "Device codename: $DEVICE_CODENAME"',
        '    echo "ROM version: ${ROM_VERSION:-unknown}"',
        '    echo "output_type: $OUTPUT_TYPE"',
        '    echo "vbmeta_mode: $VBMETA_MODE"',
        '    echo "vbmeta_patch_strategy: ${VBMETA_PATCH_STRATEGY:-unknown}"',
        '    echo "super.img size: $(file_size "$OUTPUT/images/super.img")"',
        '    if [[ -f "$zip_file" ]]; then',
        '      echo "final ZIP size: $(file_size "$zip_file")"',
        '    else',
        '      echo "final ZIP size: pending"',
        '    fi',
        '    echo "Images included:"',
        "    _image_list | sed 's/^/- /'",
        '    echo "PixelDrain link: ${pd_link:-not uploaded}"',
        '    echo "GitHub Release link: ${gh_link:-not uploaded}"',
        '  } > "$OUTPUT_FINAL/build_info.txt"',
        '}',
        '',
        '_create_logs_archive() {',
        '  [[ -d "$LOGS" ]] || return 0',
        '  require_tool zip',
        '  rm -f "$OUTPUT_FINAL/logs.zip"',
        '  (cd "$LOGS" && zip -qr "$OUTPUT_FINAL/logs.zip" .) || warn "Could not create logs.zip"',
        '}',
        '',
        'package_fastboot_zip() {',
        '  log "Packaging fastboot ZIP"',
        '  log "Checking zip tool"',
        '  require_tool zip',
        '  log "Checking sha256sum tool"',
        '  require_tool sha256sum',
        '',
        '  local zip_name="${BUILD_NAME}_${DEVICE_CODENAME}_fastboot.zip"',
        '  local zip_file="$OUTPUT_FINAL/$zip_name"',
        '',
        '  [[ -d "$OUTPUT/images" ]] || die "Missing directory: $OUTPUT/images"',
        '  [[ -s "$OUTPUT/images/super.img" ]] || die "Missing required package image: $OUTPUT/images/super.img"',
        '  [[ -s "$OUTPUT/images/vbmeta.img" ]] || die "Missing required package image: $OUTPUT/images/vbmeta.img"',
        '',
        '  rm -rf "$OUTPUT_FINAL/images" "$OUTPUT_FINAL/bin"',
        '  mkdir -p "$OUTPUT_FINAL/images" "$OUTPUT_FINAL/bin/windows"',
        '',
        '  log "Staging images"',
        '  if ! cp -al "$OUTPUT/images"/*.img "$OUTPUT_FINAL/images/" 2>/dev/null; then',
        '    warn "Hardlink image staging failed; falling back to copy"',
        '    cp -f "$OUTPUT/images"/*.img "$OUTPUT_FINAL/images/" || die "Failed to stage fastboot images"',
        '  fi',
        '  find "$OUTPUT_FINAL/images" -maxdepth 1 -type f -name \'*.img\' | grep -q . || die "No images were staged"',
        '',
        '  log "Staging Windows fastboot files"',
        '  _stage_windows_platform_tools',
        '',
        '  log "Generating Windows flash scripts"',
        '  _write_windows_install_and_format_data',
        '  _write_windows_install_upgrade',
        '  _write_windows_format_data_only',
        '  grep -n -- \'%fastboot% flash vbmeta_ab images\\\\vbmeta.img\' "$OUTPUT_FINAL/windows_install_and_format_data.bat" || true',
        '  grep -n -- \'%fastboot% flash vbmeta_system_ab images\\\\vbmeta_system.img\' "$OUTPUT_FINAL/windows_install_and_format_data.bat" || true',
        '  grep -n -- \'%fastboot% flash vbmeta_vendor_ab images\\\\vbmeta_vendor.img\' "$OUTPUT_FINAL/windows_install_and_format_data.bat" || true',
        '',
        '  log "Generating build_info sidecar"',
        '  refresh_build_info',
        '  log "Generating sha256sums"',
        '  generate_pre_zip_sha256sums',
        '  [[ -s "$OUTPUT_FINAL/sha256sums.txt" ]] || die "sha256sums.txt was not created"',
        '',
        '  log "Creating logs archive sidecar"',
        '  _create_logs_archive',
        '',
        '  rm -f "$zip_file"',
        '  log "Creating ZIP"',
        '  df -h || true',
        '  du -sh "$OUTPUT" "$OUTPUT/images" "$OUTPUT_FINAL" "$INPUT" "$EXTRACTED" 2>/dev/null || true',
        '  if ! (',
        '    cd "$OUTPUT_FINAL" &&',
        '      zip -r -0 "$zip_name" \\',
        '        bin \\',
        '        images \\',
        '        windows_install_and_format_data.bat \\',
        '        windows_install_upgrade.bat \\',
        '        windows_format_data_only.bat \\',
        '        sha256sums.txt',
        '  ); then',
        '    df -h || true',
        '    du -sh "$OUTPUT" "$OUTPUT/images" "$OUTPUT_FINAL" 2>/dev/null || true',
        '    die "zip packaging failed"',
        '  fi',
        '  [[ -s "$zip_file" ]] || die "Final fastboot ZIP was not created"',
        '  log "ZIP created: $zip_file size=$(file_size "$zip_file") bytes ($(human_size "$zip_file"))"',
        '  log "Refreshing final build_info"',
        '  refresh_build_info',
        '  log "Refreshing final checksums"',
        '  generate_pre_zip_sha256sums',
        '  generate_final_zip_sha256',
        '}',
    ],
    'core/vbmeta_patch.sh': [
        '#!/usr/bin/env bash',
        'set -euo pipefail',
        '# Rewritten by scripts/rewrite_multiline_files.py using explicit line lists.',
        '',
        '_vbmeta_flag_value() {',
        '  case "$VBMETA_MODE" in',
        "    0) printf '0' ;;",
        "    1) printf '1' ;;",
        "    2) printf '2' ;;",
        "    3) printf '3' ;;",
        '    *) die "Unsupported vbmeta_mode=$VBMETA_MODE" ;;',
        '  esac',
        '}',
        '',
        '_vbmeta_log_name() {',
        '  local img="$1"',
        '  printf \'%s\' "${img%.img}"',
        '}',
        '',
        '_write_vbmeta_info() {',
        '  local path="$1"',
        '  local out="$2"',
        '  local label="$3"',
        '  if command -v avbtool >/dev/null 2>&1; then',
        '    avbtool info_image --image "$path" > "$out" 2>&1 || {',
        '      echo "avbtool info_image failed for $label" > "$out"',
        '      return 1',
        '    }',
        '  else',
        '    python3 - "$path" > "$out" <<\'PY\'',
        'import struct',
        'import sys',
        '',
        'path = sys.argv[1]',
        'with open(path, "rb") as f:',
        '    magic = f.read(4)',
        '    if magic != b"AVB0":',
        '        raise SystemExit("not an AVB vbmeta image")',
        '    f.seek(0x78)',
        '    flags = struct.unpack(">I", f.read(4))[0]',
        'print("Fallback AVB info")',
        'print(f"Flags: {flags}")',
        'PY',
        '  fi',
        '}',
        '',
        '_patch_vbmeta_header_flags() {',
        '  local img="$1"',
        '  local flags="$2"',
        '  python3 - "$img" "$flags" <<\'PY\'',
        'import os',
        'import struct',
        'import sys',
        '',
        'path = sys.argv[1]',
        'flags = int(sys.argv[2])',
        'before = os.path.getsize(path)',
        'with open(path, "r+b") as f:',
        '    magic = f.read(4)',
        '    if magic != b"AVB0":',
        '        raise SystemExit("not an AVB vbmeta image")',
        '    f.seek(0x78)',
        '    f.write(struct.pack(">I", flags))',
        'after = os.path.getsize(path)',
        'if before != after:',
        '    raise SystemExit(f"vbmeta size changed: before={before} after={after}")',
        'PY',
        '}',
        '',
        '_verify_vbmeta_flags() {',
        '  local after_log="$1"',
        '  local expected="$2"',
        '  grep -Eq "Flags:[[:space:]]+$expected" "$after_log"',
        '}',
        '',
        'patch_vbmeta_images() {',
        '  mkdir -p "$LOGS"',
        '  : > "$LOGS/vbmeta_patch.txt"',
        '  local strategy="${VBMETA_PATCH_STRATEGY:-binary}"',
        '',
        '  if [[ "$VBMETA_MODE" == "0" ]]; then',
        '    {',
        '      echo "vbmeta patch disabled"',
        '      echo "strategy=none"',
        '      echo "mode=0"',
        '    } | tee -a "$LOGS/vbmeta_patch.txt"',
        '    return 0',
        '  fi',
        '',
        '  log "VBMETA_MODE=$VBMETA_MODE"',
        '  log "VBMETA_PATCH_STRATEGY=$strategy"',
        '',
        '  case "$strategy" in',
        '    binary) ;;',
        '    none)',
        '      log "vbmeta patch strategy none; keeping vbmeta images stock"',
        '      {',
        '        echo "strategy=none"',
        '        echo "mode=$VBMETA_MODE"',
        '      } | tee -a "$LOGS/vbmeta_patch.txt"',
        '      return 0',
        '      ;;',
        '    fastboot_flags)',
        '      die "fastboot_flags is not allowed for the public DeadZone fastboot package; use VBMETA_PATCH_STRATEGY=binary"',
        '      ;;',
        '    *)',
        '      die "Unknown VBMETA_PATCH_STRATEGY=$strategy"',
        '      ;;',
        '  esac',
        '',
        '  local flags img path name before_log after_log',
        '  flags="$(_vbmeta_flag_value)"',
        '  {',
        '    echo "strategy=binary"',
        '    echo "mode=$VBMETA_MODE"',
        '    echo "flags=$flags"',
        '    echo "patch_method=avb_header_offset_0x78"',
        '  } | tee -a "$LOGS/vbmeta_patch.txt"',
        '',
        '  for img in ${VBMETA_IMAGES:-vbmeta.img vbmeta_system.img vbmeta_vendor.img}; do',
        '    path="$OUTPUT/images/$img"',
        '    if [[ "$img" == "vbmeta.img" && ! -s "$path" ]]; then',
        '      die "Required vbmeta image is missing: $path"',
        '    fi',
        '    [[ -s "$path" ]] || continue',
        '',
        '    name="$(_vbmeta_log_name "$img")"',
        '    before_log="$LOGS/vbmeta_${name}_before.txt"',
        '    after_log="$LOGS/vbmeta_${name}_after.txt"',
        '',
        '    log "Binary patching $img with flags=$flags"',
        '    echo "patching=$img" | tee -a "$LOGS/vbmeta_patch.txt"',
        '    _write_vbmeta_info "$path" "$before_log" "$img" || die "Could not read AVB info before patch for $img"',
        '    _patch_vbmeta_header_flags "$path" "$flags" >> "$LOGS/vbmeta_patch.txt" 2>&1 || die "binary vbmeta patch failed for $img"',
        '    _write_vbmeta_info "$path" "$after_log" "$img" || die "Could not read AVB info after patch for $img"',
        '    _verify_vbmeta_flags "$after_log" "$flags" || die "binary vbmeta patch failed for $img; expected Flags: $flags"',
        '    echo "patched=$img flags=$flags" | tee -a "$LOGS/vbmeta_patch.txt"',
        '  done',
        '}',
    ],
    'main.sh': [
        '#!/usr/bin/env bash',
        'set -euo pipefail',
        '# Rewritten by scripts/rewrite_multiline_files.py using explicit line lists.',
        '',
        'export WORKSPACE="${WORKSPACE:-$(pwd)}"',
        'export BIN="$WORKSPACE/bin"',
        'export INPUT="$WORKSPACE/input"',
        'export EXTRACTED="$WORKSPACE/extracted"',
        'export OUTPUT="$WORKSPACE/output"',
        'export OUTPUT_FINAL="$WORKSPACE/output_final"',
        'export LOGS="$OUTPUT/logs"',
        'export DEVICES="$WORKSPACE/devices"',
        'export PATH="$BIN:$PATH"',
        '',
        'source "$WORKSPACE/core/utils.sh"',
        'source "$WORKSPACE/core/unpacker.sh"',
        'source "$WORKSPACE/core/repacker.sh"',
        'source "$WORKSPACE/core/fs_detect.sh"',
        'source "$WORKSPACE/core/collect_images.sh"',
        'source "$WORKSPACE/core/vbmeta_patch.sh"',
        'source "$WORKSPACE/core/package_fastboot.sh"',
        'source "$WORKSPACE/core/upload_release.sh"',
        'source "$WORKSPACE/core/validate_build.sh"',
        '',
        '_err_trap() {',
        '  local rc=$?',
        '  local src="${BASH_SOURCE[1]:-${BASH_SOURCE[0]}}"',
        '  local line="${BASH_LINENO[0]:-${LINENO}}"',
        '  local func="${FUNCNAME[1]:-main}"',
        '  echo "::error file=$src,line=$line::Command failed in $func rc=$rc: $BASH_COMMAND" >&2',
        '  exit "$rc"',
        '}',
        'trap _err_trap ERR',
        '',
        'run_step() {',
        '  local name="$1"',
        '  shift',
        '  log "STEP: $name start"',
        '  "$@"',
        '  log "STEP: $name done"',
        '}',
        '',
        'cleanup_for_fastboot_package() {',
        '  case "$OUTPUT_TYPE" in',
        '    fastboot_zip|full_release) ;;',
        '    *) return 0 ;;',
        '  esac',
        '',
        '  section "Fastboot Package Cleanup"',
        '  log "Disk usage before cleanup"',
        '  df -h || true',
        '  du -sh "$INPUT" "$EXTRACTED" "$OUTPUT" "$OUTPUT/images" "$OUTPUT_FINAL" "$LOGS" 2>/dev/null || true',
        '',
        '  if [[ -n "${ROM_FILE:-}" && -f "$ROM_FILE" ]]; then',
        '    rm -f "$ROM_FILE"',
        '    log "Removed downloaded OTA: $ROM_FILE"',
        '  fi',
        '  rm -rf "$INPUT/ota" "$INPUT/payload.bin"',
        '',
        '  local part',
        '  for part in $DYNAMIC_PARTITIONS; do',
        '    rm -f \\',
        '      "$EXTRACTED/$part.img" \\',
        '      "$EXTRACTED/${part}.raw.img" \\',
        '      "$EXTRACTED/${part}_a.img" \\',
        '      "$EXTRACTED/${part}_a.raw.img" \\',
        '      "$EXTRACTED/${part}_b.img" \\',
        '      "$EXTRACTED/${part}_b.raw.img"',
        '  done',
        '',
        '  find "$OUTPUT" -maxdepth 1 -type f -name \'super.img.zst\' -delete 2>/dev/null || true',
        '  [[ -s "$OUTPUT/images/super.img" ]] || die "cleanup removed output/images/super.img"',
        '',
        '  log "Disk usage after cleanup"',
        '  df -h || true',
        '  du -sh "$INPUT" "$EXTRACTED" "$OUTPUT" "$OUTPUT/images" "$OUTPUT_FINAL" "$LOGS" 2>/dev/null || true',
        '}',
        '',
        'main() {',
        '  local rom_url="${1:-${ROM_URL:-}}"',
        '  export DEVICE_CODENAME="${2:-${DEVICE_CODENAME:-}}"',
        '  export SKIP_PATCHES="${3:-${SKIP_PATCHES:-true}}"',
        '  export OUTPUT_TYPE="${4:-${OUTPUT_TYPE:-super_zst}}"',
        '  export FS_MODE="${5:-${FS_MODE:-erofs}}"',
        '  export VBMETA_MODE="${6:-${VBMETA_MODE:-3}}"',
        '  export PATCH_LEVEL="${7:-${PATCH_LEVEL:-none}}"',
        '  export BUILD_NAME="${BUILD_NAME:-DeadZone_v1}"',
        '  export UPLOAD_PIXELDRAIN="${UPLOAD_PIXELDRAIN:-false}"',
        '  export NOTIFY_TELEGRAM="${NOTIFY_TELEGRAM:-false}"',
        '  export CREATE_GITHUB_RELEASE="${CREATE_GITHUB_RELEASE:-false}"',
        '  export VBMETA_PATCH_STRATEGY="${VBMETA_PATCH_STRATEGY:-}"',
        '',
        '  [[ -n "$rom_url" ]] || die "Usage: ./main.sh <ROM_URL> <DEVICE_CODENAME> [SKIP_PATCHES] [OUTPUT_TYPE] [FS_MODE] [VBMETA_MODE] [PATCH_LEVEL]"',
        '  [[ -n "$DEVICE_CODENAME" ]] || die "device_codename is required"',
        '  case "$OUTPUT_TYPE" in',
        '    super_zst|fastboot_zip|full_release) ;;',
        '    *) die "Unsupported output_type=$OUTPUT_TYPE" ;;',
        '  esac',
        '  case "$FS_MODE" in preserve|erofs) ;; *) die "Unsupported fs_mode=$FS_MODE" ;; esac',
        '  case "$VBMETA_MODE" in 0|1|2|3) ;; *) die "Unsupported vbmeta_mode=$VBMETA_MODE" ;; esac',
        '  case "$PATCH_LEVEL" in none|safe|full) ;; *) die "Unsupported patch_level=$PATCH_LEVEL" ;; esac',
        '  if [[ -z "$VBMETA_PATCH_STRATEGY" ]]; then',
        '    case "$OUTPUT_TYPE" in',
        '      fastboot_zip|full_release) VBMETA_PATCH_STRATEGY=binary ;;',
        '      *) VBMETA_PATCH_STRATEGY=binary ;;',
        '    esac',
        '    export VBMETA_PATCH_STRATEGY',
        '  fi',
        '',
        '  section "DeadZone ROM Kitchen"',
        '  log "Device codename: $DEVICE_CODENAME"',
        '  log "Build name: $BUILD_NAME"',
        '  log "Skip patches: $SKIP_PATCHES"',
        '  log "Output type: $OUTPUT_TYPE"',
        '  log "fs_mode: $FS_MODE"',
        '  log "vbmeta_mode: $VBMETA_MODE"',
        '  log "vbmeta_patch_strategy: $VBMETA_PATCH_STRATEGY"',
        '  log "patch_level: $PATCH_LEVEL"',
        '',
        '  if [[ "$SKIP_PATCHES" != "true" || "$PATCH_LEVEL" != "none" ]]; then',
        '    warn "ROM modifications are intentionally disabled for this build server version"',
        '  fi',
        '',
        '  prepare_env',
        '  load_device_defaults',
        '  load_device_profile || die "Missing device profile: devices/$DEVICE_CODENAME.conf"',
        '  fetch_rom "$rom_url"',
        '  export ROM_URL="$rom_url"',
        '  detect_rom_version "$rom_url"',
        '',
        '  section "Payload Extraction"',
        '  extract_payload_all_images',
        '  detect_partition_images',
        '  detect_dynamic_filesystems',
        '',
        '  section "Super Build"',
        '  build_super_image',
        '  validate_super_image',
        '',
        '  if [[ "$OUTPUT_TYPE" == "fastboot_zip" || "$OUTPUT_TYPE" == "full_release" ]]; then',
        '    cleanup_for_fastboot_package',
        '    section "Fastboot Package"',
        '    run_step collect_fastboot_images collect_fastboot_images',
        '    run_step patch_vbmeta_images patch_vbmeta_images',
        '    run_step package_fastboot_zip package_fastboot_zip',
        '    run_step validate_build validate_build',
        '    if [[ "$CREATE_GITHUB_RELEASE" == "true" || "$UPLOAD_PIXELDRAIN" == "true" || "$NOTIFY_TELEGRAM" == "true" ]]; then',
        '      section "Release Uploads"',
        '      run_step upload_release_artifacts upload_release_artifacts',
        '      run_step validate_build validate_build',
        '    fi',
        '  else',
        '    compress_super_image',
        '    validate_super_zst',
        '  fi',
        '',
        '  section "Done"',
        '  if [[ "$OUTPUT_TYPE" == "super_zst" ]]; then',
        '    log "Output path: $OUTPUT/super.img.zst"',
        '  else',
        '    log "Output path: $OUTPUT_FINAL/${BUILD_NAME}_${DEVICE_CODENAME}_fastboot.zip"',
        '  fi',
        '  log "Logs path: $LOGS"',
        '}',
        '',
        'main "$@"',
    ],
    'core/repacker.sh': [
        '#!/usr/bin/env bash',
        'set -euo pipefail',
        '# Rewritten by scripts/rewrite_multiline_files.py using explicit line lists.',
        '',
        'build_super_image() {',
        '  require_tool lpmake',
        '',
        '  prepare_super_lpmake_context',
        '',
        '  local -a cmd',
        '  build_lpmake_cmd cmd "$OUTPUT/images/super.img" true "$SUPER_OUTPUT_FORMAT"',
        '',
        '  printf \'%q \' "${cmd[@]}" > "$LOGS/lpmake-command.log"',
        '  printf \'\\n\' >> "$LOGS/lpmake-command.log"',
        '',
        '  log "Running lpmake"',
        '  "${cmd[@]}" 2>&1 | tee "$LOGS/lpmake.log"',
        '',
        '  [[ -s "$OUTPUT/images/super.img" ]] || die "lpmake did not create a non-empty $OUTPUT/images/super.img"',
        '  log "Final fastboot super image: output/images/super.img"',
        '  log "Output path: $OUTPUT/images/super.img"',
        '  log "super.img size: $(file_size "$OUTPUT/images/super.img") bytes ($(human_size "$OUTPUT/images/super.img"))"',
        '  file "$OUTPUT/images/super.img" 2>&1 | tee "$LOGS/super_file_type.txt" || true',
        '  file_size "$OUTPUT/images/super.img" > "$LOGS/super_size.txt"',
        '}',
        '',
        'prepare_super_lpmake_context() {',
        '  local metadata_source="profile"',
        '  if load_device_profile; then',
        '    metadata_source="profile"',
        '  elif _load_super_metadata_from_image; then',
        '    metadata_source="lpdump"',
        '  else',
        '    _fail_missing_profile',
        '  fi',
        '',
        '  _validate_super_profile',
        '',
        '  SUPER_TOTAL_IMAGE_SIZE=0',
        '  SUPER_TOTAL_B_IMAGE_SIZE=0',
        '  local part img size container fs b_img b_size group_a_size group_b_size',
        "  while IFS=$'\\t' read -r part img size container fs; do",
        '    [[ -n "${part:-}" ]] || continue',
        '    SUPER_TOTAL_IMAGE_SIZE=$((SUPER_TOTAL_IMAGE_SIZE + size))',
        '    b_img="$EXTRACTED/${part}_b.img"',
        '    if [[ -s "$b_img" ]]; then',
        '      b_size="$(file_size "$b_img")"',
        '      SUPER_TOTAL_B_IMAGE_SIZE=$((SUPER_TOTAL_B_IMAGE_SIZE + b_size))',
        '    fi',
        '  done < "$WORKSPACE/partitions.tsv"',
        '',
        '  SUPER_SLOT_MODE="${SUPER_SLOT_MODE:-A}"',
        '  SUPER_OUTPUT_FORMAT="${SUPER_OUTPUT_FORMAT:-sparse}"',
        '  SUPER_ACTIVE_SLOT="${SUPER_ACTIVE_SLOT:-a}"',
        '  SUPER_INACTIVE_SLOT="b"',
        '  local group_basename="${SUPER_GROUP_BASENAME:-${DYNAMIC_PARTITION_GROUP_NAME:-qti_dynamic_partitions}}"',
        '  SUPER_ACTIVE_GROUP="${DYNAMIC_PARTITION_GROUP_NAME:-$group_basename}"',
        '  SUPER_INACTIVE_GROUP=""',
        '',
        '  case "$SUPER_SLOT_MODE" in',
        '    A|AB|VAB) ;;',
        '    *) die "Unsupported SUPER_SLOT_MODE=$SUPER_SLOT_MODE" ;;',
        '  esac',
        '  case "$SUPER_OUTPUT_FORMAT" in',
        '    sparse|raw) ;;',
        '    *) die "Unsupported SUPER_OUTPUT_FORMAT=$SUPER_OUTPUT_FORMAT" ;;',
        '  esac',
        '  case "$SUPER_ACTIVE_SLOT" in',
        '    a) SUPER_INACTIVE_SLOT="b" ;;',
        '    b) SUPER_INACTIVE_SLOT="a" ;;',
        '    *) die "Unsupported SUPER_ACTIVE_SLOT=$SUPER_ACTIVE_SLOT" ;;',
        '  esac',
        '',
        '  if [[ "$SUPER_SLOT_MODE" == "AB" || "$SUPER_SLOT_MODE" == "VAB" ]]; then',
        '    SUPER_ACTIVE_GROUP="${group_basename}_${SUPER_ACTIVE_SLOT}"',
        '    SUPER_INACTIVE_GROUP="${group_basename}_${SUPER_INACTIVE_SLOT}"',
        '    group_a_size="${DYNAMIC_PARTITION_GROUP_SIZE_A:-$DYNAMIC_PARTITION_GROUP_SIZE}"',
        '    if [[ -n "${DYNAMIC_PARTITION_GROUP_SIZE_B:-}" ]]; then',
        '      group_b_size="$DYNAMIC_PARTITION_GROUP_SIZE_B"',
        '    elif (( SUPER_TOTAL_B_IMAGE_SIZE > 0 )); then',
        '      group_b_size="$DYNAMIC_PARTITION_GROUP_SIZE"',
        '    else',
        '      group_b_size=1048576',
        '    fi',
        '  else',
        '    group_a_size="$DYNAMIC_PARTITION_GROUP_SIZE"',
        '    group_b_size=0',
        '  fi',
        '  SUPER_GROUP_A_SIZE="$group_a_size"',
        '  SUPER_GROUP_B_SIZE="$group_b_size"',
        '',
        '  log "Super metadata source: $metadata_source"',
        '  log "Super size: $SUPER_SIZE"',
        '  log "SUPER_SLOT_MODE: $SUPER_SLOT_MODE"',
        '  log "SUPER_OUTPUT_FORMAT: $SUPER_OUTPUT_FORMAT"',
        '  log "SUPER_ACTIVE_SLOT: $SUPER_ACTIVE_SLOT"',
        '  log "Active group name: $SUPER_ACTIVE_GROUP"',
        '  [[ -n "$SUPER_INACTIVE_GROUP" ]] && log "Inactive group name: $SUPER_INACTIVE_GROUP"',
        '  log "Active image total size: $SUPER_TOTAL_IMAGE_SIZE"',
        '  log "Inactive image total size: $SUPER_TOTAL_B_IMAGE_SIZE"',
        '  log "Group A size: $SUPER_GROUP_A_SIZE"',
        '  log "Group B size: $SUPER_GROUP_B_SIZE"',
        '  log "Use --virtual-ab: $([[ "$SUPER_SLOT_MODE" == "VAB" ]] && printf true || printf false)"',
        '',
        '  if (( SUPER_TOTAL_IMAGE_SIZE > SUPER_GROUP_A_SIZE )); then',
        '    die "Active partition images exceed group A size: images=$SUPER_TOTAL_IMAGE_SIZE group=$SUPER_GROUP_A_SIZE"',
        '  fi',
        '  if (( SUPER_TOTAL_B_IMAGE_SIZE > SUPER_GROUP_B_SIZE )); then',
        '    die "Inactive partition images exceed group B size: images=$SUPER_TOTAL_B_IMAGE_SIZE group=$SUPER_GROUP_B_SIZE"',
        '  fi',
        '}',
        '',
        'build_lpmake_cmd() {',
        '  local -n out_cmd="$1"',
        '  local output_path="$2"',
        '  local include_images="$3"',
        '  local output_format="$4"',
        '  local part img size container fs b_img b_size',
        '',
        '  out_cmd=(',
        '    lpmake',
        '    --metadata-size "$SUPER_METADATA_SIZE"',
        '    --metadata-slots "$SUPER_METADATA_SLOTS"',
        '    --super-name "${SUPER_NAME:-super}"',
        '    --device "super:$SUPER_SIZE"',
        '    --group "$SUPER_ACTIVE_GROUP:$SUPER_GROUP_A_SIZE"',
        '  )',
        '  if [[ "$SUPER_SLOT_MODE" == "AB" || "$SUPER_SLOT_MODE" == "VAB" ]]; then',
        '    out_cmd+=(--group "$SUPER_INACTIVE_GROUP:$SUPER_GROUP_B_SIZE")',
        '  fi',
        '  [[ "$SUPER_SLOT_MODE" == "VAB" ]] && out_cmd+=(--virtual-ab)',
        '  [[ "$output_format" == "sparse" ]] && out_cmd+=(--sparse)',
        '',
        "  while IFS=$'\\t' read -r part img size container fs; do",
        '    [[ -n "${part:-}" ]] || continue',
        '    if [[ "$SUPER_SLOT_MODE" == "A" ]]; then',
        '      local lp_name="${part}${PARTITION_SUFFIX:-}"',
        '      out_cmd+=(--partition "$lp_name:readonly:$size:$SUPER_ACTIVE_GROUP")',
        '      [[ "$include_images" == "true" ]] && out_cmd+=(--image "$lp_name=$img")',
        '    else',
        '      local active_lp="${part}_${SUPER_ACTIVE_SLOT}"',
        '      local inactive_lp="${part}_${SUPER_INACTIVE_SLOT}"',
        '      out_cmd+=(--partition "$active_lp:readonly:$size:$SUPER_ACTIVE_GROUP")',
        '      [[ "$include_images" == "true" ]] && out_cmd+=(--image "$active_lp=$img")',
        '',
        '      b_img="$EXTRACTED/${part}_${SUPER_INACTIVE_SLOT}.img"',
        '      if [[ -s "$b_img" ]]; then',
        '        b_size="$(file_size "$b_img")"',
        '        out_cmd+=(--partition "$inactive_lp:readonly:$b_size:$SUPER_INACTIVE_GROUP")',
        '        [[ "$include_images" == "true" ]] && out_cmd+=(--image "$inactive_lp=$b_img")',
        '      else',
        '        out_cmd+=(--partition "$inactive_lp:readonly:0:$SUPER_INACTIVE_GROUP")',
        '      fi',
        '    fi',
        '  done < "$WORKSPACE/partitions.tsv"',
        '',
        '  out_cmd+=(--output "$output_path")',
        '}',
        '',
        '_load_super_metadata_from_image() {',
        '  if ! command -v lpdump >/dev/null 2>&1; then',
        '    warn "lpdump is not available; using devices/$DEVICE_CODENAME.conf if present"',
        '    return 1',
        '  fi',
        '',
        '  local candidate',
        '  for candidate in "$EXTRACTED/super.img" "$INPUT/super.img" "$INPUT/super_raw.img"; do',
        '    [[ -f "$candidate" ]] || continue',
        '    log "Reading exact super metadata from: $candidate"',
        '    lpdump "$candidate" > "$LOGS/lpdump.log" 2>&1 || return 1',
        '',
        '    SUPER_SIZE="$(file_size "$candidate")"',
        '    SUPER_METADATA_SIZE="$(awk \'/Metadata max size:/ {for (i=1; i<=NF; i++) if ($i ~ /^[0-9]+$/) {print $i; exit}}\' "$LOGS/lpdump.log")"',
        '    SUPER_METADATA_SLOTS="$(awk \'/Metadata slot count:/ {for (i=1; i<=NF; i++) if ($i ~ /^[0-9]+$/) {print $i; exit}}\' "$LOGS/lpdump.log")"',
        '    DYNAMIC_PARTITION_GROUP_NAME="$(awk \'/Name:/ {name=$2} /Maximum size:/ && name != "" {print name; exit}\' "$LOGS/lpdump.log")"',
        '    DYNAMIC_PARTITION_GROUP_SIZE="$(awk \'/Maximum size:/ {for (i=1; i<=NF; i++) if ($i ~ /^[0-9]+$/) {print $i; exit}}\' "$LOGS/lpdump.log")"',
        '',
        '    [[ -n "${SUPER_METADATA_SIZE:-}" && -n "${SUPER_METADATA_SLOTS:-}" ]] || return 1',
        '    [[ -n "${DYNAMIC_PARTITION_GROUP_NAME:-}" && -n "${DYNAMIC_PARTITION_GROUP_SIZE:-}" ]] || return 1',
        '',
        '    export SUPER_SIZE SUPER_METADATA_SIZE SUPER_METADATA_SLOTS DYNAMIC_PARTITION_GROUP_NAME DYNAMIC_PARTITION_GROUP_SIZE',
        '    return 0',
        '  done',
        '',
        '  return 1',
        '}',
        '',
        'compress_super_image() {',
        '  require_tool zstd',
        '  log "Compressing super.img to super.img.zst"',
        '  zstd -T0 -19 -f "$OUTPUT/images/super.img" -o "$OUTPUT/super.img.zst" 2>&1 | tee "$LOGS/zstd.log"',
        '  log "Output path: $OUTPUT/super.img.zst"',
        '  log "super.img.zst size: $(file_size "$OUTPUT/super.img.zst") bytes ($(human_size "$OUTPUT/super.img.zst"))"',
        '}',
        '',
        'validate_super_image() {',
        '  [[ -s "$OUTPUT/images/super.img" ]] || die "super.img is missing or empty"',
        '  require_tool lpdump',
        '  require_tool lpmake',
        '',
        '  local validation_source="$OUTPUT/images/super.img"',
        '  if [[ "${SUPER_OUTPUT_FORMAT:-sparse}" == "sparse" ]]; then',
        '    log "SUPER_OUTPUT_FORMAT=sparse; validating with metadata-only non-sparse image"',
        '    validation_source="$LOGS/super_metadata.img"',
        '    local -a metadata_cmd',
        '    build_lpmake_cmd metadata_cmd "$validation_source" false raw',
        '    printf \'%q \' "${metadata_cmd[@]}" > "$LOGS/lpmake-metadata-command.log"',
        '    printf \'\\n\' >> "$LOGS/lpmake-metadata-command.log"',
        '    log "Metadata validation image: output/logs/super_metadata.img"',
        '    "${metadata_cmd[@]}" 2>&1 | tee "$LOGS/lpmake_metadata.log"',
        '    [[ -s "$validation_source" ]] || die "metadata validation image was not created"',
        '  fi',
        '',
        '  log "lpdump validation source: ${validation_source#$WORKSPACE/}"',
        '  file "$OUTPUT/images/super.img" || true',
        '  file "$validation_source" || true',
        '  lpdump "$validation_source" > "$LOGS/lpdump_super.txt" 2>&1 || die "lpdump validation failed for ${validation_source#$WORKSPACE/}"',
        '',
        '  local slot_mode="${SUPER_SLOT_MODE:-A}"',
        '  if [[ "$slot_mode" == "AB" || "$slot_mode" == "VAB" ]]; then',
        '    local part missing_active=() missing_inactive=()',
        '    local active_slot="${SUPER_ACTIVE_SLOT:-a}"',
        '    local inactive_slot',
        '    case "$active_slot" in',
        '      a) inactive_slot="b" ;;',
        '      b) inactive_slot="a" ;;',
        '      *) die "Unsupported SUPER_ACTIVE_SLOT=$active_slot" ;;',
        '    esac',
        '',
        '    for part in $DYNAMIC_PARTITIONS; do',
        '      grep -q "${part}_${active_slot}" "$LOGS/lpdump_super.txt" || missing_active+=("${part}_${active_slot}")',
        '      grep -q "${part}_${inactive_slot}" "$LOGS/lpdump_super.txt" || missing_inactive+=("${part}_${inactive_slot}")',
        '    done',
        '',
        '    if [[ ${#missing_active[@]} -gt 0 ]]; then',
        '      die "$slot_mode metadata missing active partition entries: ${missing_active[*]}"',
        '    fi',
        '    if [[ ${#missing_inactive[@]} -gt 0 ]]; then',
        '      die "$slot_mode metadata missing inactive _${inactive_slot} partition entries: ${missing_inactive[*]}"',
        '    fi',
        '  fi',
        '}',
        '',
        '_validate_super_profile() {',
        '  local missing=()',
        '  [[ -n "${SUPER_SIZE:-}" ]] || missing+=("SUPER_SIZE")',
        '  if [[ "${SUPER_SLOT_MODE:-A}" == "A" ]]; then',
        '    [[ -n "${DYNAMIC_PARTITION_GROUP_NAME:-}" ]] || missing+=("DYNAMIC_PARTITION_GROUP_NAME")',
        '  fi',
        '  [[ -n "${DYNAMIC_PARTITION_GROUP_SIZE:-}" ]] || missing+=("DYNAMIC_PARTITION_GROUP_SIZE")',
        '  [[ -n "${SUPER_METADATA_SIZE:-}" ]] || missing+=("SUPER_METADATA_SIZE")',
        '  [[ -n "${SUPER_METADATA_SLOTS:-}" ]] || missing+=("SUPER_METADATA_SLOTS")',
        '',
        '  if [[ ${#missing[@]} -gt 0 ]]; then',
        '    die "Device profile devices/$DEVICE_CODENAME.conf is missing: ${missing[*]}"',
        '  fi',
        '}',
        '',
        '_fail_missing_profile() {',
        '  cat >&2 <<EOF',
        '[ERROR] Could not auto-read super metadata, and no device profile was found.',
        'Create: devices/$DEVICE_CODENAME.conf',
        '',
        'Required fields:',
        'SUPER_SIZE=',
        'DYNAMIC_PARTITION_GROUP_NAME=',
        'DYNAMIC_PARTITION_GROUP_SIZE=',
        'SUPER_METADATA_SIZE=',
        'SUPER_METADATA_SLOTS=',
        'SUPER_NAME=super',
        'PARTITION_SUFFIX=',
        '',
        'Tip: get exact values from a stock super.img using lpdump, or from the device board config.',
        'EOF',
        '  exit 1',
        '}',
    ],
    'core/validate_build.sh': [
        '#!/usr/bin/env bash',
        'set -euo pipefail',
        '# Rewritten by scripts/rewrite_multiline_files.py using explicit line lists.',
        '',
        'validate_super_zst() {',
        '  [[ -s "$OUTPUT/images/super.img" ]] || die "output/images/super.img is missing or empty"',
        '  [[ -s "$OUTPUT/super.img.zst" ]] || die "output/super.img.zst is missing or empty"',
        '}',
        '',
        '_check_no_crlf() {',
        '  local file',
        "  while IFS= read -r -d '' file; do",
        '    if grep -Iq . "$file" && grep -q $\'\\r\' "$file"; then',
        '      die "CRLF detected in shell script: $file"',
        '    fi',
        '  done < <(find "$WORKSPACE" -path "$WORKSPACE/.git" -prune -o -type f -name \'*.sh\' -print0)',
        '}',
        '',
        '_check_shell_syntax() {',
        '  local file',
        "  while IFS= read -r -d '' file; do",
        '    bash -n "$file" || die "Shell syntax check failed: $file"',
        '  done < <(find "$WORKSPACE" -path "$WORKSPACE/.git" -prune -o -type f -name \'*.sh\' -print0)',
        '}',
        '',
        '_check_no_secret_leaks() {',
        '  local secret',
        '  for secret in "${PIXELDRAIN_API_KEY:-}" "${TELEGRAM_BOT_TOKEN:-}" "${TELEGRAM_CHAT_ID:-}" "${GITHUB_TOKEN:-}"; do',
        '    [[ -n "$secret" ]] || continue',
        '    if grep -R --binary-files=without-match -F "$secret" "$LOGS" "$OUTPUT_FINAL" >/dev/null 2>&1; then',
        '      die "A configured secret appears in generated logs or output files"',
        '    fi',
        '  done',
        '}',
        '',
        'validate_build() {',
        '  local zip_file="$OUTPUT_FINAL/${BUILD_NAME}_${DEVICE_CODENAME}_fastboot.zip"',
        '',
        '  [[ -s "$OUTPUT/images/super.img" ]] || die "output/images/super.img is missing or empty"',
        '  if [[ "${SUPER_OUTPUT_FORMAT:-sparse}" == "sparse" ]]; then',
        '    [[ -s "$LOGS/super_metadata.img" ]] || die "Sparse super metadata validation image is missing"',
        '    [[ -s "$LOGS/lpdump_super.txt" ]] || die "Sparse super lpdump validation log is missing"',
        '  else',
        '    require_tool lpdump',
        '    lpdump "$OUTPUT/images/super.img" >/dev/null 2>&1 || die "lpdump validation failed"',
        '  fi',
        '',
        '  if [[ "${SUPER_SLOT_MODE:-A}" == "AB" || "${SUPER_SLOT_MODE:-A}" == "VAB" ]]; then',
        '    local part active_slot inactive_slot',
        '    active_slot="${SUPER_ACTIVE_SLOT:-a}"',
        '    case "$active_slot" in',
        '      a) inactive_slot="b" ;;',
        '      b) inactive_slot="a" ;;',
        '      *) die "Unsupported SUPER_ACTIVE_SLOT=$active_slot" ;;',
        '    esac',
        '    for part in $DYNAMIC_PARTITIONS; do',
        '      grep -q "${part}_${active_slot}" "$LOGS/lpdump_super.txt" || die "${SUPER_SLOT_MODE:-AB} metadata missing active partition entry: ${part}_${active_slot}"',
        '      grep -q "${part}_${inactive_slot}" "$LOGS/lpdump_super.txt" || die "${SUPER_SLOT_MODE:-AB} metadata missing inactive partition entry: ${part}_${inactive_slot}"',
        '    done',
        '  fi',
        '',
        '  local img',
        '  for img in ${REQUIRED_FASTBOOT_IMAGES:-boot.img init_boot.img vendor_boot.img vbmeta.img}; do',
        '    [[ -s "$OUTPUT/images/$img" ]] || die "Required image missing: output/images/$img"',
        '  done',
        '',
        '  [[ -s "$zip_file" ]] || die "Final fastboot ZIP is missing or empty: $zip_file"',
        '  [[ -s "$OUTPUT_FINAL/sha256sums.txt" ]] || die "sha256sums.txt is missing"',
        '  [[ -s "$OUTPUT_FINAL/build_info.txt" ]] || die "build_info.txt is missing"',
        '  [[ -d "$OUTPUT_FINAL/images" ]] || die "Final images folder is missing"',
        '  [[ -s "$OUTPUT_FINAL/bin/windows/fastboot.exe" ]] || die "Missing package file: bin/windows/fastboot.exe"',
        '  [[ -s "$OUTPUT_FINAL/bin/windows/AdbWinApi.dll" ]] || die "Missing package file: bin/windows/AdbWinApi.dll"',
        '  [[ -s "$OUTPUT_FINAL/bin/windows/AdbWinUsbApi.dll" ]] || die "Missing package file: bin/windows/AdbWinUsbApi.dll"',
        '',
        '  for file in windows_install_and_format_data.bat windows_install_upgrade.bat windows_format_data_only.bat; do',
        '    [[ -s "$OUTPUT_FINAL/$file" ]] || die "Missing package file: $file"',
        '  done',
        '  [[ -s "$OUTPUT_FINAL/images/vbmeta.img" ]] || die "Final ZIP staging is missing images/vbmeta.img"',
        '',
        '  grep -q -- \'--disable-verity\' "$OUTPUT_FINAL/windows_install_and_format_data.bat" && die "Windows format script must not contain --disable-verity"',
        '  grep -q -- \'--disable-verification\' "$OUTPUT_FINAL/windows_install_and_format_data.bat" && die "Windows format script must not contain --disable-verification"',
        '  grep -q -- \'fastboot -w\' "$OUTPUT_FINAL/windows_install_and_format_data.bat" && die "Windows format script must not use fastboot -w"',
        '  grep -q -- \'--disable-verity\' "$OUTPUT_FINAL/windows_install_upgrade.bat" && die "Windows upgrade script must not contain --disable-verity"',
        '  grep -q -- \'--disable-verification\' "$OUTPUT_FINAL/windows_install_upgrade.bat" && die "Windows upgrade script must not contain --disable-verification"',
        '  grep -q -- \'fastboot -w\' "$OUTPUT_FINAL/windows_install_upgrade.bat" && die "Windows upgrade script must not use fastboot -w"',
        '',
        '  grep -qF \'%fastboot% flash vbmeta_ab images\\vbmeta.img\' "$OUTPUT_FINAL/windows_install_and_format_data.bat" || die "Windows format script missing vbmeta flash"',
        '  grep -qF \'%fastboot% flash vbmeta_system_ab images\\vbmeta_system.img\' "$OUTPUT_FINAL/windows_install_and_format_data.bat" || die "Windows format script missing vbmeta_system flash"',
        '  grep -qF \'%fastboot% flash vbmeta_vendor_ab images\\vbmeta_vendor.img\' "$OUTPUT_FINAL/windows_install_and_format_data.bat" || die "Windows format script missing vbmeta_vendor flash"',
        '  grep -qF \'%fastboot% flash super images\\super.img\' "$OUTPUT_FINAL/windows_install_and_format_data.bat" || die "Windows format script missing super flash"',
        '  grep -qF \'%fastboot% erase metadata\' "$OUTPUT_FINAL/windows_install_and_format_data.bat" || die "Windows format script missing metadata erase"',
        '  grep -qF \'%fastboot% erase userdata\' "$OUTPUT_FINAL/windows_install_and_format_data.bat" || die "Windows format script missing userdata erase"',
        '',
        '  if [[ "${VBMETA_MODE:-0}" == "3" && "${VBMETA_PATCH_STRATEGY:-binary}" == "binary" ]]; then',
        '    for name in vbmeta vbmeta_system vbmeta_vendor; do',
        '      [[ -s "$LOGS/vbmeta_${name}_after.txt" ]] || die "Missing vbmeta after log: vbmeta_${name}_after.txt"',
        '      grep -Eq \'Flags:[[:space:]]+3\' "$LOGS/vbmeta_${name}_after.txt" || die "vbmeta_${name}_after.txt does not contain Flags: 3"',
        '    done',
        '  fi',
        '',
        '  if ! unzip -t "$zip_file" >/dev/null; then',
        '    die "Final ZIP failed integrity check"',
        '  fi',
        '',
        '  unzip -l "$zip_file" > "$LOGS/public_zip_listing.txt"',
        '  for required in \\',
        '    bin/windows/fastboot.exe \\',
        '    bin/windows/AdbWinApi.dll \\',
        '    bin/windows/AdbWinUsbApi.dll \\',
        '    images/super.img \\',
        '    images/boot.img \\',
        '    images/init_boot.img \\',
        '    images/vendor_boot.img \\',
        '    images/vbmeta.img \\',
        '    windows_install_and_format_data.bat \\',
        '    windows_install_upgrade.bat \\',
        '    windows_format_data_only.bat; do',
        '    grep -q "$required" "$LOGS/public_zip_listing.txt" || die "Public ZIP missing: $required"',
        '  done',
        '  for forbidden in \\',
        "    'logs/' \\",
        "    'README.txt' \\",
        "    'build_info.txt' \\",
        "    'super_metadata.img' \\",
        "    'lpmake' \\",
        "    'payload-dumper' \\",
        "    'lpdump' \\",
        "    'filesystems.txt' \\",
        "    'partitions.log'; do",
        '    grep -q "$forbidden" "$LOGS/public_zip_listing.txt" && die "Public ZIP contains forbidden entry: $forbidden"',
        '  done',
        '',
        '  _check_shell_syntax',
        '  _check_no_crlf',
        '  _check_no_secret_leaks',
        '}',
    ],
    'core/upload_release.sh': [
        '#!/usr/bin/env bash',
        'set -euo pipefail',
        '# Rewritten by scripts/rewrite_multiline_files.py using explicit line lists.',
        '',
        'GITHUB_RELEASE_ASSET_MAX_BYTES="${GITHUB_RELEASE_ASSET_MAX_BYTES:-2147483648}"',
        '',
        '_bool_true() {',
        '  case "${1:-false}" in true|True|TRUE|1|yes|YES) return 0 ;; *) return 1 ;; esac',
        '}',
        '',
        '_release_tag() {',
        '  printf \'%s-%s-%s\' "$BUILD_NAME" "$DEVICE_CODENAME" "${ROM_VERSION:-unknown}"',
        '}',
        '',
        '_zip_path() {',
        '  printf \'%s/%s_%s_fastboot.zip\' "$OUTPUT_FINAL" "$BUILD_NAME" "$DEVICE_CODENAME"',
        '}',
        '',
        '_append_upload_link() {',
        '  local key="$1"',
        '  local value="$2"',
        '  touch "$OUTPUT_FINAL/upload_links.txt"',
        '  grep -v "^$key=" "$OUTPUT_FINAL/upload_links.txt" > "$OUTPUT_FINAL/upload_links.tmp" 2>/dev/null || true',
        '  printf \'%s=%s\\n\' "$key" "$value" >> "$OUTPUT_FINAL/upload_links.tmp"',
        '  mv -f "$OUTPUT_FINAL/upload_links.tmp" "$OUTPUT_FINAL/upload_links.txt"',
        '}',
        '',
        '_github_asset_allowed() {',
        '  local file="$1"',
        '  local size',
        '  [[ -s "$file" ]] || return 1',
        '  size="$(file_size "$file")"',
        '  if (( size >= GITHUB_RELEASE_ASSET_MAX_BYTES )); then',
        '    warn "Skipping GitHub Release upload for $(basename "$file"): size $size exceeds GitHub asset limit $GITHUB_RELEASE_ASSET_MAX_BYTES"',
        '    return 1',
        '  fi',
        '  return 0',
        '}',
        '',
        '_zip_too_large_for_github() {',
        '  local zip_file="$(_zip_path)"',
        '  [[ -s "$zip_file" ]] || return 1',
        '  (( $(file_size "$zip_file") >= GITHUB_RELEASE_ASSET_MAX_BYTES ))',
        '}',
        '',
        '_pixeldrain_url() {',
        '  grep \'^PIXELDRAIN_URL=\' "$OUTPUT_FINAL/upload_links.txt" 2>/dev/null | cut -d= -f2- || true',
        '}',
        '',
        '_upload_github_release() {',
        '  _bool_true "$CREATE_GITHUB_RELEASE" || {',
        '    warn "GitHub Release upload disabled"',
        '    return',
        '  }',
        '  [[ -n "${GITHUB_TOKEN:-}" ]] || {',
        '    warn "GITHUB_TOKEN is missing; skipping GitHub Release"',
        '    return',
        '  }',
        '  require_tool gh',
        '',
        '  local tag title zip_file logs_zip url asset uploaded_any',
        '  tag="$(_release_tag)"',
        '  title="$BUILD_NAME $DEVICE_CODENAME ${ROM_VERSION:-unknown}"',
        '  zip_file="$(_zip_path)"',
        '  logs_zip="$OUTPUT_FINAL/logs.zip"',
        '  uploaded_any=false',
        '  [[ -s "$zip_file" ]] || die "Cannot upload missing ZIP: $zip_file"',
        '',
        '  if [[ -d "$OUTPUT_FINAL/logs" ]]; then',
        '    (cd "$OUTPUT_FINAL" && zip -qr logs.zip logs) || warn "Could not create logs.zip"',
        '  fi',
        '',
        '  export GH_TOKEN="$GITHUB_TOKEN"',
        '  if gh release view "$tag" >/dev/null 2>&1; then',
        '    log "Updating existing GitHub Release: $tag"',
        '  else',
        '    gh release create "$tag" --title "$title" --notes-file "$OUTPUT_FINAL/build_info.txt" >/dev/null',
        '  fi',
        '',
        '  url="$(gh release view "$tag" --json url -q .url 2>/dev/null || true)"',
        '  if [[ -n "$url" ]]; then',
        '    _append_upload_link "GITHUB_RELEASE_URL" "$url"',
        '    refresh_build_info',
        '    generate_pre_zip_sha256sums',
        '  fi',
        '',
        '  if _github_asset_allowed "$zip_file"; then',
        '    gh release upload "$tag" "$zip_file" --clobber >/dev/null',
        '    uploaded_any=true',
        '  else',
        '    _append_upload_link "GITHUB_RELEASE_ZIP_SKIPPED" "true"',
        '    _append_upload_link "GITHUB_RELEASE_ZIP_SKIP_REASON" "larger_than_2GiB"',
        '  fi',
        '',
        '  for asset in \\',
        '    "$zip_file.sha256" \\',
        '    "$OUTPUT_FINAL/build_info.txt" \\',
        '    "$OUTPUT_FINAL/sha256sums.txt" \\',
        '    "$OUTPUT_FINAL/upload_links.txt" \\',
        '    "$logs_zip"; do',
        '    [[ -s "$asset" ]] || continue',
        '    if _github_asset_allowed "$asset"; then',
        '      gh release upload "$tag" "$asset" --clobber >/dev/null',
        '      uploaded_any=true',
        '    fi',
        '  done',
        '',
        '  [[ "$uploaded_any" == "true" ]] || warn "No GitHub Release assets were uploaded"',
        '}',
        '',
        '_upload_pixeldrain() {',
        '  _bool_true "$UPLOAD_PIXELDRAIN" || {',
        '    warn "PixelDrain upload disabled"',
        '    if _zip_too_large_for_github; then',
        '      warn "Final ZIP is too large for GitHub Release and PixelDrain upload is disabled."',
        '    fi',
        '    return',
        '  }',
        '  if [[ -z "${PIXELDRAIN_API_KEY:-}" ]]; then',
        '    warn "PIXELDRAIN_API_KEY is missing; skipping PixelDrain upload"',
        '    if _zip_too_large_for_github; then',
        '      die "PixelDrain upload required because final ZIP is too large for GitHub Release, but PIXELDRAIN_API_KEY is missing"',
        '    fi',
        '    return',
        '  fi',
        '  require_tool curl',
        '  require_tool jq',
        '',
        '  local zip_file response id',
        '  zip_file="$(_zip_path)"',
        '  [[ -s "$zip_file" ]] || die "Cannot upload missing ZIP: $zip_file"',
        '  log "Uploading fastboot ZIP to PixelDrain"',
        '  response="$(curl -fsS -u ":$PIXELDRAIN_API_KEY" -F "file=@$zip_file" "https://pixeldrain.com/api/file" 2>/dev/null)" || {',
        '    if _zip_too_large_for_github; then',
        '      die "PixelDrain upload failed and final ZIP is too large for GitHub Release"',
        '    fi',
        '    warn "PixelDrain upload failed"',
        '    return',
        '  }',
        '  id="$(printf \'%s\' "$response" | jq -r \'.id // empty\')"',
        '  if [[ -z "$id" ]]; then',
        '    if _zip_too_large_for_github; then',
        '      die "PixelDrain upload failed and final ZIP is too large for GitHub Release"',
        '    fi',
        '    warn "PixelDrain upload failed"',
        '    return',
        '  fi',
        '  _append_upload_link "PIXELDRAIN_URL" "https://pixeldrain.com/u/$id"',
        '}',
        '',
        '_notify_telegram() {',
        '  _bool_true "$NOTIFY_TELEGRAM" || {',
        '    warn "Telegram notification disabled"',
        '    return',
        '  }',
        '  if [[ -z "${TELEGRAM_BOT_TOKEN:-}" || -z "${TELEGRAM_CHAT_ID:-}" ]]; then',
        '    warn "Telegram secrets are missing; skipping notification"',
        '    return',
        '  fi',
        '  require_tool curl',
        '',
        '  local zip_file sha pd gh size skip_note pd_note message',
        '  zip_file="$(_zip_path)"',
        '  sha="$(cut -d\' \' -f1 "$zip_file.sha256" 2>/dev/null || true)"',
        '  pd="$(_pixeldrain_url)"',
        '  gh="$(grep \'^GITHUB_RELEASE_URL=\' "$OUTPUT_FINAL/upload_links.txt" 2>/dev/null | cut -d= -f2- || true)"',
        '  size="$(human_size "$zip_file")"',
        '  skip_note=""',
        '  pd_note=""',
        '  if _zip_too_large_for_github; then',
        '    skip_note="GitHub Release ZIP skipped because file is larger than 2GiB."',
        '    if [[ -z "$pd" ]]; then',
        '      pd_note="PixelDrain link missing; ZIP too large for GitHub Release."',
        '    fi',
        '  fi',
        '  message=$(cat <<EOF',
        'Build completed',
        'Device: $DEVICE_CODENAME',
        'Build: $BUILD_NAME',
        'ROM version: ${ROM_VERSION:-unknown}',
        'Final ZIP: $(basename "$zip_file")',
        'ZIP size: $size',
        'SHA256: $sha',
        'PixelDrain: ${pd:-not uploaded}',
        'GitHub Release: ${gh:-not uploaded}',
        '${skip_note}',
        '${pd_note}',
        'EOF',
        ')',
        '  curl -fsS -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \\',
        '    -d "chat_id=${TELEGRAM_CHAT_ID}" \\',
        '    --data-urlencode "text=$message" >/dev/null || warn "Telegram notification failed"',
        '}',
        '',
        'upload_release_artifacts() {',
        '  touch "$OUTPUT_FINAL/upload_links.txt"',
        '  _upload_pixeldrain',
        '  refresh_build_info',
        '  generate_pre_zip_sha256sums',
        '  _upload_github_release',
        '  _notify_telegram',
        '}',
    ],
    'devices/zircon.conf': [
        '# Rewritten by scripts/rewrite_multiline_files.py using explicit line lists.',
        '# Redmi Note 13 Pro+ (zircon)',
        '# Verify SUPER_SIZE and DYNAMIC_PARTITION_GROUP_SIZE with:',
        '# fastboot getvar partition-size:super',
        'DEVICE_CODENAME=zircon',
        'DEVICE_BRAND=Xiaomi',
        'DEVICE_SOC=MediaTek',
        'SUPER_SIZE=9126805504',
        'SUPER_SLOT_MODE=VAB',
        'SUPER_OUTPUT_FORMAT=sparse',
        'SUPER_ACTIVE_SLOT=a',
        'SUPER_GROUP_BASENAME=qti_dynamic_partitions',
        'DYNAMIC_PARTITION_GROUP_NAME=qti_dynamic_partitions',
        'DYNAMIC_PARTITION_GROUP_SIZE=9122611200',
        'SUPER_METADATA_SIZE=65536',
        'SUPER_METADATA_SLOTS=2',
        'METADATA_SLOTS=2',
        'SUPER_NAME=super',
        'PARTITION_SUFFIX=_a',
        'FASTBOOT_SLOT_MODE=ab_suffix',
        '',
        'DYNAMIC_PARTITIONS="system product system_ext vendor vendor_dlkm system_dlkm odm odm_dlkm mi_ext"',
        'REQUIRED_FASTBOOT_IMAGES="boot.img init_boot.img vendor_boot.img vbmeta.img"',
        'OPTIONAL_FASTBOOT_IMAGES="dtbo.img vbmeta_system.img vbmeta_vendor.img vendor_kernel_boot.img recovery.img logo.img lk.img tee.img scp.img spmfw.img audio_dsp.img dpm.img mcupm.img pi_img.img gz.img md1img.img my_bigball.img my_carrier.img my_company.img my_engineering.img my_heytap.img my_manifest.img my_preload.img my_product.img my_region.img my_stock.img"',
        'VBMETA_IMAGES="vbmeta.img vbmeta_system.img vbmeta_vendor.img"',
        'VBMETA_PATCH_STRATEGY=binary',
        '',
        'SUPER_PARTITIONS=(',
        '  system',
        '  product',
        '  system_ext',
        '  vendor',
        '  vendor_dlkm',
        '  system_dlkm',
        '  odm',
        '  odm_dlkm',
        '  mi_ext',
        ')',
    ],
    'devices/template.conf': [
        '# Rewritten by scripts/rewrite_multiline_files.py using explicit line lists.',
        '# Device profile template for DeadZone fastboot builds.',
        '# Copy this file to devices/<codename>.conf and fill values from stock firmware',
        '# or lpdump/board config. Keep device-specific metadata here, not in scripts.',
        '',
        'DEVICE_CODENAME=',
        'DEVICE_BRAND=',
        'DEVICE_SOC=',
        '',
        '# super partition metadata',
        'SUPER_SIZE=',
        'SUPER_SLOT_MODE=VAB',
        'SUPER_OUTPUT_FORMAT=sparse',
        'SUPER_ACTIVE_SLOT=a',
        'SUPER_GROUP_BASENAME=qti_dynamic_partitions',
        'DYNAMIC_PARTITION_GROUP_NAME=',
        'DYNAMIC_PARTITION_GROUP_SIZE=',
        'SUPER_METADATA_SIZE=65536',
        'METADATA_SLOTS=2',
        'SUPER_METADATA_SLOTS=2',
        'SUPER_NAME=super',
        'PARTITION_SUFFIX=_a',
        '',
        '# Optional explicit slot group sizes. If unset, VAB keeps active images in',
        '# DYNAMIC_PARTITION_GROUP_SIZE and gives inactive zero-size metadata a small group.',
        '# DYNAMIC_PARTITION_GROUP_SIZE_A=',
        '# DYNAMIC_PARTITION_GROUP_SIZE_B=',
        '',
        '# Dynamic partition images expected from payload.bin.',
        'DYNAMIC_PARTITIONS="system product system_ext vendor vendor_dlkm system_dlkm odm odm_dlkm mi_ext"',
        '',
        '# Fastboot package image policy.',
        'REQUIRED_FASTBOOT_IMAGES="boot.img init_boot.img vendor_boot.img vbmeta.img"',
        'OPTIONAL_FASTBOOT_IMAGES="dtbo.img vbmeta_system.img vbmeta_vendor.img vendor_kernel_boot.img recovery.img logo.img lk.img tee.img scp.img spmfw.img audio_dsp.img dpm.img mcupm.img pi_img.img gz.img md1img.img my_bigball.img my_carrier.img my_company.img my_engineering.img my_heytap.img my_manifest.img my_preload.img my_product.img my_region.img my_stock.img"',
        'VBMETA_IMAGES="vbmeta.img vbmeta_system.img vbmeta_vendor.img"',
        '',
        '# Use ab_suffix for targets like boot_ab/vbmeta_ab, or single for boot/vbmeta.',
        'FASTBOOT_SLOT_MODE=ab_suffix',
    ],
}

for path, lines in FILES.items():
    write_lf(path, lines)
    print(f"wrote {path}: {len(lines)} lines")
